PVRUM_URL = "${TOPDIR}/../proprietary/pvr_um_vgpu_img"
SRC_URI_r8a7795 = "file://${PVRUM_URL}"
SRC_URI_r8a7796 = "file://${PVRUM_URL}"
SRC_URI_r8a77965 = "file://${PVRUM_URL}"
S = "${WORKDIR}/${PVRUM_URL}"
